import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import LoadingProvider from "./loading-provider";
import { Providers } from "./providers";
import { AuthProvider } from '@/providers/AuthProvider';
import { cookies } from "next/headers";
import ClientWrapper from './ClientWrapper';
import { GoogleOAuthProvider } from '@react-oauth/google';

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-roboto",
  preload: true,
  fallback: ['system-ui', 'arial'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get('token')?.value;
  const pathname = typeof window !== 'undefined' ? window.location.pathname : '';
  return (
    <html lang="en" className={roboto.variable}>
      <body className="antialiased">
        <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID || ''}>
          <Providers>
            <AuthProvider token={token}>
              <LoadingProvider>
                <ClientWrapper>{children}</ClientWrapper>
              </LoadingProvider>
            </AuthProvider>
          </Providers>
        </GoogleOAuthProvider>
      </body>
    </html>
  );
}
