import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import LoadingProvider from "./loading-provider";
import { Providers } from "./providers";
import { AuthProvider } from '@/providers/AuthProvider';
import { cookies } from "next/headers";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: 'swap',
  variable: "--font-roboto",
  preload: true,
  fallback: ['system-ui', 'arial'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = cookies();
  const token = cookieStore.get('token')?.value;
  return (
    <html lang="en" className={roboto.variable}>
      <body className="antialiased">
        <Providers>
          <AuthProvider token={token}>
            <LoadingProvider>{children}</LoadingProvider>
          </AuthProvider>
        </Providers>
      </body>
    </html>
  );
}
